name: ecommerce_customer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  flutter_otp_text_field: ^1.1.2+1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  http: ^1.2.1
  lottie: ^3.1.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  dropdown_search: ^5.0.6
  # jiffy: ^6.3.0
  url_launcher: ^6.2.5
  rating_dialog: ^2.0.4
  animations: ^2.0.11
  liquid_swipe: ^3.1.0
  animated_text_kit: ^4.2.2
  flutter_onboarding_slider: ^1.0.11
  awesome_dialog: ^3.2.0
  firebase_messaging: ^14.7.21
  firebase_core: ^2.27.2
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  equatable: ^2.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/audios/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf