// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXU8JpwJK_SivijLYtcxusn9CqDPwu-3U',
    appId: '1:1014638655969:web:3abd1ce8554298df063aa0',
    messagingSenderId: '1014638655969',
    projectId: 'ecommerce-customer-466d1',
    authDomain: 'ecommerce-customer-466d1.firebaseapp.com',
    storageBucket: 'ecommerce-customer-466d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Xjv_eNtRlLkhyYmGNcM0HpvOGzPkkaw',
    appId: '1:1014638655969:android:9afe09c09024997f063aa0',
    messagingSenderId: '1014638655969',
    projectId: 'ecommerce-customer-466d1',
    storageBucket: 'ecommerce-customer-466d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChLtJC58R3hok7jIHBR3xTrDGtoUTdjN8',
    appId: '1:1014638655969:ios:407c396d001d73ec063aa0',
    messagingSenderId: '1014638655969',
    projectId: 'ecommerce-customer-466d1',
    storageBucket: 'ecommerce-customer-466d1.appspot.com',
    iosBundleId: 'com.example.ecommerceCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChLtJC58R3hok7jIHBR3xTrDGtoUTdjN8',
    appId: '1:1014638655969:ios:1aba16b71f18850f063aa0',
    messagingSenderId: '1014638655969',
    projectId: 'ecommerce-customer-466d1',
    storageBucket: 'ecommerce-customer-466d1.appspot.com',
    iosBundleId: 'com.example.ecommerceCustomer.RunnerTests',
  );
}
